favicon: null
name: knechtus
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
purpose: []
color:
  saturation: 0.1875
  brandStrength: 0.5224903007037938
  lightness: 0.375
  brandColors:
    - '#6499F4'
    - '#0B0A0D'
    - '#C6FFFD'
    - '#A3994B'
    - '#C50F26'
  rhythmicContrast: 0.4336157268844545
typography_spectrum: 0.18097
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 0.3100359
analytics:
  twitter: null
  google: null
  facebook: null
