name: knechtus
favicon: null
layout_spectrum: 0.93507
typography_spectrum: 0.18097
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: knechtus
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#97aa01'
    - '#321601'
    - '#fd0301'
    - '#06889e'
    - '#81e2ce'
  brandStrength: 0.8125
  lightness: 0.375
  saturation: 0.1875
  rhythmicContrast: 0.4336157268844545
purpose: []
