favicon: null
name: knechtus
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.1875
  brandStrength: 0.5224903007037938
  rhythmicContrast: 0.4336157268844545
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  lightness: 0.375
typography_spectrum: 0.18097
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 0.3100359
analytics:
  twitter: null
  google: null
  facebook: null
