name: knechtus
favicon: null
layout_spectrum: 0.20792146865278482
typography_spectrum: 0.37955414643511176
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.5224903007037938
  lightness: 0.31336122448556125
  saturation: 0.07231957628391683
  rhythmicContrast: 0.4336157268844545
purpose: []
